name: Hassfest

on:
  push:
    branches: ["main", "master"]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  hassfest:
    name: hassfest validation
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
      - name: Run Hassfest
        uses: "home-assistant/actions/hassfest@master"
